behaviors:
  RobotAgentBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 1024
      learning_rate: 0.0007
      beta: 0.001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: false
      hidden_units: 64
      num_layers: 1
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 5000
    time_horizon: 32
    summary_freq: 500
